### ISSUE TITLE
Disable 1 on 1/Private Messages to Hubot

### ISSUE THREAD

**Issue by tessellare** [hipchat/hubot-hipchat#176]
Our Hubot has some privileged commands it can run, so I'd like to keep it confined to one or two rooms with authorized users. I can keep it from joining rooms it is invited to by setting "HUBOT_HIPCHAT_JOIN_ROOMS_ON_INVITE" to false, however, this doesn't prevent someone from opening a private conversation with it and sending commands directly. I believe I could limit access with with an authorization script, but I'd rather disable the feature altogether.

**Comment by rbergman** [comment]
A typical solution for this problem is to set script-specific env vars (or other persistent server-side configuration) containing lists of authorized JIDs for sensitive commands.  More sophisticated solutions use auth scripts, of course.

Alternately, you could submit a PR that uses another env var to optionally disable connector.onPrivateMessage.
