### ISSUE TITLE
Sending files

### ISSUE THREAD

**Issue by thasmo** [hipchat/hubot-hipchat#184]
As far as I can see it's not possible to send/upload files with hubot for hipchat. That would make a nice feature as hubot could process stuff and upload files which then chould be downloaded.

**Comment by kwketh** [comment]
+1

**Comment by rbergman** [comment]
The HipChat REST API allows uploading files -- I'd suggest starting there.  If anyone is passionate enough about adding support for this to the HipChat adapter, please feel free to open a PR instead of an issue -- while bugs may still get fixed, major features like this is are unlikely without third-party PRs.
