### ISSUE TITLE
Get HipChat Room ID from XMPP JID

### ISSUE THREAD

**Issue by nickolaskraus-wf** [hipchat/hubot-hipchat#295]
I have been trying to devise a way to get the HipChat Room ID from the XMPP JID. I am using ```roomNameFromJid()``` to get the quais room name, but this is not the actual name of the room as far as HipChat is concerned. The end goal here is to use a Hubot clone to determine the Room ID and therefore API ID, so that the HipChat API can be used for a specific room.

This is not an issue, per se, but I would like to hear your suggestions.

**Comment by luciomr** [comment]
I thought I was the only one needing this. Any news regarding this?
My code connects to Hipchat via XMPP but responds to commands using Hipchat API (html responses), so this is crucial.

**Comment by nickolaskraus-wf** [comment]
@luciomr The only solution I could come up with was using a database to store a mapping of XMPP to Room ID, then hit an endpoint to get the Room ID from the XMPP. From there, the HipChat API can provide you the actual room name. I talked to Atlassian and this was the only solution they could come up with as well and were not inclined to extend their API to include the XMPP as a query parameter.

**Comment by luciomr** [comment]
Okay, I am dealing with this in a very unorthodox way:

I am first getting the [base information of all rooms](https://www.hipchat.com/docs/apiv2/method/get_all_rooms). 
The response of that endpoint doesn't provide me the xmpp_room_jid -> hipchat_api_id relationship, but using that response, I am creating several requests to [get the detailed info of a room](https://www.hipchat.com/docs/apiv2/method/get_room). The response of this endpoint does have xmpp_jid of the room.

The problem is that Hipchat API has a [VERY LOW rate limit](https://developer.atlassian.com/hipchat/guide/hipchat-rest-api/api-rate-limits), so now I am working on bypassing that limit, which will be tricky, since for the Cloud version of Hipchat you're only allowed 100 requests every 5 minutes (only Hipchat Integrations have a rate limit bumped to 500 requests every 5 minutes).

**Comment by luciomr** [comment]
> were not inclined to extend their API to include the XMPP as a query parameter.

Jeez.... They want all of us to use Integrations instead of XMPP. Problem is that I would use Integrations if you could use them in chats 1-to-1 and not just in rooms. I asked them if they would support global integrations to be used in chats 1-to-1 and they said they're 'working on it'...

This is proving to be more troublesome than it should be due these limitations.

**Comment by nickolaskraus-wf** [comment]
Yes, so each time you want to determine the Room ID or room name, you need to create and parse 500+ requests. Not efficient. This is why we've stopped development of our hubot.
