### ISSUE TITLE
Allow 'color' formatting on messages

### ISSUE THREAD

**Issue by arnlaugsson** [hipchat/hubot-hipchat#43]
See: https://www.hipchat.com/docs/api/method/rooms/message

It would be really nice to be able to send red, yellow, gray, green and blue messages. The rest api allows this, but I haven't found a way with this module.

**Comment by AdamAld** [comment]
@amaltson is correct. The node wrapper [hipchatter](https://github.com/charltoons/hipchatter) can be used instead very simply.

[Hubot](https://github.com/github/hubot) + [hubot-hipchat](https://github.com/hipchat/hubot-hipchat) + [hipchatter](https://github.com/charltoons/hipchatter): 
I currently use these three in conjunction to continue to easily connect to Hipchat and manipulate Hubot command. Whenever a command is brought up that needs to alert Hipchat with an error, Hipchatter is used within a Hubot CoffeeScript in order to easily customize a message.

If you have any questions or concerns about my implementation of those please let me know!

**Comment by crazed** [comment]
@AdamAld how do you convert the msg.message.room to something that can be used with hipchatter? It seems they are lowercased and spaces swapped with underscores, rather than the proper hipchat room name.
